### ISSUE TITLE
Aceto is full!

### ISSUE THREAD

**Issue by L3viathan** [L3viathan/aceto#1]
With the release of Aceto 1.6, we've filled up all of printable ASCII.

To add more commands, we have to make a choice. I'm currently leaning towards option C, but I'm still undecided. Approval of @sarnthil would also be required.

### A) Removing commands (breaking backwards-compatibility; i.e. in Aceto 2.0)

Pro: 

- we would keep the 1 character = 1 byte property
- relatively easy to do
- there are rarely used commands
- could also combine/overload commands

Contra:

- we lose commands and break backwards compatibility
- this is only a temporary fix

### B) Using a specific codepage (not UTF-8)

Pro:

- about twice the amount of characters until we hit another limit, this could be enough forever

Contra:

- we'd have difficulties representing non-ASCII strings (in literals)
- annoying to edit code
- annoying to implement
- might not be enough forever

### C) Using more characters (but keeping UTF-8)

Pro:

- practically unlimited commands
- backwards compatible
- 1 byte per character isn't guaranteed now either

Contra:

- We lose the at the moment usual property of 1 byte per character

### D) Using control characters

Pro:

- doable right now
- backwards compatible

Contra:

- only a handful of characters
- annoying to view; doesn't line up (at least in Vim)
- annoying to enter
- not printable

**Comment by L3viathan** [comment]
There is a fifth option that was touched on in **(A)**, but I'll explicitly state it here:

### E) Overloading commands

There are many commands that only work in a certain context and could have different meanings for other contexts. For example, the potentiation command `F` has no meaning when the top stack element is a string. There are many examples of this, and we could avoid a decision using it for a while.

**Comment by sarnthil** [comment]
I think it would be better to first go for E and overload commands that can be overloaded. We could even overload commands that have a name that is not proper now and use the remaining character for a future command. If doing that is not enough then I approve going later for option C.
