### ISSUE TITLE
`,` doesn't work if an interactive environment is unavailable

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [L3viathan/aceto#27]
For example: [Try it online!](https://tio.run/##S0xOLcn//1@n4P//kozMYgUgKs7PTeUqSk3MyalUSM7Pz@HKzCsoLQEA "Aceto – Try It Online") errors out when trying to run `getch`, which I assume is trying to read from the keyboard or something similar.

**Comment by L3viathan** [comment]
I pushed a new branch called [issue27](https://github.com/aceto/aceto/tree/issue27) where I test for `os.isatty`. Can you easily test whether this works?

**Comment by ConorOBrien-Foxx** [comment]
@L3viathan  I think you can try piping something from STDIN to test it. I'll try it locally however

**Comment by ConorOBrien-Foxx** [comment]
@L3viathan  I think you can try piping something from STDIN to test it. I tried testing it locally but this current approach doesn't seem to work on windows:

```
C:\Users\conorob\Programming\aceto (issue27 -> origin)
λ aceto.py
Traceback (most recent call last):
  File "C:\Users\conorob\Programming\aceto\aceto.py", line 19, in <module>
    import tty
  File "C:\Users\conorob\AppData\Local\Programs\Python\Python36-32\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
```

**Comment by L3viathan** [comment]
Seems to work for me, with the Aceto program

```
rp
,p
```

the command `echo "foobar" | ./aceto.py thatprogram.act` prints `"oobarf"`, which is what I would expect.

Windows is not supported by Aceto at the moment.

**Comment by ConorOBrien-Foxx** [comment]
cool, good to know
