### ISSUE TITLE
Aceto interpreter not working on Mac: Syntax error

### ISSUE THREAD

**Issue by razetime** [L3viathan/aceto#30]
I tried running aceto.py and got this error:
```python
$ python aceto.py

  File "aceto.py", line 153
    print(Colors.FAIL.value, file=sys.stderr, end='')
                                 ^
SyntaxError: invalid syntax
```

I don't know what's wrong.

**Comment by L3viathan** [comment]
On macOS, `python` means Python 2; Aceto requires a recent version of Python 3, see if `python3 aceto.py` works. On macOS you may have to install python3 first, for example using [Homebrew](https://brew.sh/):

    brew install python3

**Comment by razetime** [comment]
I used python3 and this came up: 
```
$ python3 aceto.py 
Traceback (most recent call last):
  File "aceto.py", line 29, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'
```

**Comment by L3viathan** [comment]
Right. You can try `pip3 install docopt`, then it should work afterwards, but I should really package this properly.

**Comment by L3viathan** [comment]
I upgraded a bunch of things internally now, try `pip3 install acetolang`, then use the `aceto` command that should have been installed.

**Comment by razetime** [comment]
ERROR: Could not find a version that satisfies the requirement acetolang (from versions: none)
ERROR: No matching distribution found for acetolang

The python file itself works now, but the pip command you gave me throws these errors.

**Comment by L3viathan** [comment]
I guess your Python 3 version is <3.8. There's no reason why I should make this require 3.8, I just did because that was the Python version I had available locally. I'll rebuild it for Python 3.6+ I guess.

**Comment by L3viathan** [comment]
Try if it works now.

**Comment by razetime** [comment]
Works well.
