### ISSUE TITLE
Moving the editor ("balsamico") to its own repo

### ISSUE THREAD

**Issue by L3viathan** [L3viathan/aceto#7]
The editor is independent of the language semantics itself (only shares the "syntax"). The only shared requirement is the external `hilbert_curve` dependency. It might therefore make sense to put balsamico in its own repository.

**Comment by sarnthil** [comment]
Indeed, it does make sense to move the editor to its own repository.

**Comment by L3viathan** [comment]
Then I would say we leave this issue open until that is done.

**Comment by L3viathan** [comment]
Closed by c24d442. New repository is [here](/aceto/balsamico).
